blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community Chat
    url: https://discord.gg/5pXbmVDM
    about: Ask quick questions or simply chat on the `NFToupon` community Discord server.
  - name: 💬 New Updates (Twitter)
    url: https://twitter.com/eatozee
    about: Link to our twitter account if you want to follow us and stay up to date with NFToupon news
